### ISSUE TITLE
Perfetta: images don't appear on the main page

### ISSUE THREAD

**Issue by foodista** [GavickPro/Perfetta-Free-WordPress-Theme#17]
Hi,
Perfetta is a beautiful theme for a food blog, but why I cant get images on my home page  . I have them well inside the posts. In the demo images appear as at the main page so inside the post. How can I solve this problem?

**Comment by dziudek** [comment]
Hello,

Please put featured image for your posts - then it will be displayed on the frontpage.

**Comment by foodista** [comment]
Hello ,
i didn't quite understand what do you mean. The images are already in posts, but they don't appear on the frontpage. This is my site www.foodista.ru

**Comment by dziudek** [comment]
Please read: http://www.wpbeginner.com/beginners-guide/how-to-add-featured-image-or-post-thumbnails-in-wordpress/

**Comment by foodista** [comment]
Thank you. I've did it at first, but the size of an image was to small to display beautiful on the front page. Now I understand my mistake.
